### ISSUE TITLE
Dashboard not found

### ISSUE THREAD

**Issue by rgolea** [deployd/deployd-cli#5] opened 2016-12-26 19:31 UTC
I get a 404 error on trying to open the dashboard.

**Comment by NicolasRitouet** [comment] 2016-12-27 21:10
well, it's not a bug, we decided not to add the dashboard by default.
If you need to install the dashboard, you can do so with `npm i dpd-dashboard dpd-clientlib --save`

**Comment by rgolea** [comment] 2016-12-28 12:36
oh! sorry! my bad... I thought it was a problem of mine. Maybe we should add some info at installing?

**Comment by rgolea** [comment] 2016-12-28 20:27
I will resume recording the tutorials very soon so I have to investigate everything. That might be able to be a faster way to do docs until they are properly redacted.

**Comment by BraydenGirard** [comment] 2017-06-20 15:23
# deployd-cli

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/deployd/deployd)
[![Current Version](https://img.shields.io/npm/v/deployd-cli.svg?style=flat-square)](https://www.npmjs.org/package/deployd-cli)
[![Build Status](https://img.shields.io/travis/deployd/deployd-cli.svg?style=flat-square)](http://travis-ci.org/deployd/deployd-cli)

> The [Deployd](http://www.deployd.com) Command Line Interface

:warning: This CLI is very much a work in progress. Use it at your own risk. The nodule name might change.

## Installation

`npm install dpd-cli -g`

## Prerequisites

The CLI requires [Node 4](https://nodejs.org/en/download/) or higher.  
Deployd requires a running MongoDB to start sucessfully. Check the [Deployd Requirements](https://github.com/deployd/deployd#requirements)

## Getting started

```bash
$ dpd create hello
$ cd hello
$ dpd
```

## Using the dashboard

```bash
$ npm i dpd-dashboard dpd-clientlib --save
$ dpd -d
```

## License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details

**Comment by BraydenGirard** [comment] 2017-06-20 15:23
Does this make sense? I would like to start contributing, is there a branch I can push to?

**Comment by rgolea** [comment] 2017-06-20 15:25
@BraydenGirard we work based on Pull Requests. Please read [this](https://github.com/deployd/deployd/blob/master/CONTRIBUTING.md)

**Comment by NicolasRitouet** [comment] 2017-07-20 18:39
@BraydenGirard your PR has been merged, thanks again :+1:

**Closed by NicolasRitouet** 2017-07-20 18:39 UTC
Labels: question
